let state={
  newskind:1,newskindname:null,
  //存储管理员信息
  AdmInfo:{},
  msg:{},
  visitInfo:{},
  code:Number,//判断审核类型
  code1:Number,//判断是不是二维码
  CompanyInfo:{},
  buildingId:Number,
  mobilePhoneNo:Number,
  api:'',
  imgLen:'',//判断头像是否上传
  phone:'',//登录的手机
  password:"",//登录的密码
  info:{},
  openId:'',//用户唯一标识
  message:{},//存储首页头像和欢迎词
  code11:'',
  appId:'',
  id1:'',//审核类型
  code2:'',//登录的code
  comInfo:{},//要填的公司
  bindcompany:[],
  WseeTZ:{},//查看物业通知详情
  CseeTZ:{},//查看物业通知详情
  CoManger:{},//存储公司管理员
  choosedcompany:Number,//看当前选的公司
  bindwuye:[],
  readedCo:{},//已经阅读过的公司
  notreadCo:{},//没有阅读过的公司
  WuCoXQ:{},//点击阅读和为阅读公司详情
  choosedbuild:Number,//看当前选的物业
  childMenuInfos:[],//详细设置的子设置
  address:'',
  location:null,
};
export default state
